### ISSUE TITLE
On latest commit, looks like the textures are broken.

### ISSUE THREAD

**Issue by Nucleria** [AgeCraft/AgeCraft#1]
Metal block textures are in the resources/assets/agecraft/textures/blocks/metals/block folder, but appear to have different names than what is defined in the code.

Console output:
http://pastebin.com/2DrD3HAS

**Comment by Nucleria** [comment]
Was wondering if I should fix it or if it's being fixed.

**Comment by DanielHuisman** [comment]
It was a problem in ExtendedMetadata. I will push the updated version tomorrow. Thanks for showing interest in the project ;)

**Comment by Nucleria** [comment]
Okay, thanks. I'll be ready. I saw this project a long time ago before it was given up on and then revived. I remember people hating on it, but I love the idea and hope it goes well for you.
